import NilpotentConjugacy.WordLength
import Mathlib.GroupTheory.SemidirectProduct
import Mathlib.Algebra.Group.Equiv.TypeTags
import Mathlib.Algebra.Polynomial.Div
import Mathlib.Data.Nat.Choose.Bounds
import Mathlib.Algebra.Polynomial.Eval.Defs
import Mathlib.Algebra.Group.Hom.End
import Mathlib.Data.Nat.Digits.Lemmas

/-!
Constructive word tools for the compression argument. The iterated commutator
identities below are identities in actual groups and every bound is witnessed
by words in the given generators. The general Jordan-block compression theorem
requires further coordinate estimates and error cancellation; it is not asserted
by these tools.
-/

namespace NilpotentConjugacy

variable {G : Type*} [Group G]

/-- Left-nested commutator instructions, evaluated from the right. -/
def nestedCommutator (ts : List G) (x : G) : G :=
  ts.foldr (fun t y => t * y * t⁻¹ * y⁻¹) x

/-- Length of the literal words produced by the recursive commutator construction. -/
def nestedWordCost (B n : ℕ) : ℕ → ℕ
  | 0 => n
  | d + 1 => 2 * (B + nestedWordCost B n d)

theorem nestedWordCost_identity (B n d : ℕ) :
    nestedWordCost B n d + 2 * B = 2 ^ d * (n + 2 * B) := by
  induction d with
  | zero => simp [nestedWordCost]
  | succ d ih =>
    simp only [nestedWordCost, pow_succ]
    nlinarith [ih]

/-- Literal nested commutator words have length linear in the input word lengths
when the nesting depth is fixed. -/
theorem nestedCommutator_rep {S : Set G} {B n : ℕ} {x : G}
    (ts : List G) (hx : WordRep S n x)
    (ht : ∀ t ∈ ts, WordRep S B t) :
    WordRep S (nestedWordCost B n ts.length) (nestedCommutator ts x) := by
  induction ts with
  | nil => simpa [nestedCommutator, nestedWordCost] using hx
  | cons t ts ih =>
    have hts := ih (fun u hu => ht u (by simp [hu]))
    simpa [nestedCommutator, nestedWordCost] using
      (ht t (by simp)).commutator hts

theorem nestedCommutator_rep_uniform {S : Set G} {B : ℕ} {x : G}
    (ts : List G) (hx : WordRep S B x)
    (ht : ∀ t ∈ ts, WordRep S B t) :
    WordRep S (3 * 2 ^ ts.length * B) (nestedCommutator ts x) := by
  apply (nestedCommutator_rep ts hx ht).mono
  have h := nestedWordCost_identity B B ts.length
  nlinarith

section Semidirect

variable {N H : Type*} [Group N] [Group H] (φ : H →* MulAut N)

/-- The exact normal-subgroup element obtained by a commutator. -/
def commutatorDifference (h : H) (n : N) : N := φ h n * n⁻¹

theorem semidirect_commutator (h : H) (n : N) :
    (SemidirectProduct.inr h : N ⋊[φ] H) * SemidirectProduct.inl n *
      (SemidirectProduct.inr h)⁻¹ * (SemidirectProduct.inl n)⁻¹ =
        SemidirectProduct.inl (commutatorDifference φ h n) := by
  rw [commutatorDifference, map_mul, map_inv]
  rw [SemidirectProduct.inl_aut, map_inv]

/-- Composition of the difference operators, in the order prescribed by a word. -/
def iteratedDifference (hs : List H) (n : N) : N :=
  hs.foldr (commutatorDifference φ) n

theorem nestedCommutator_inr_inl (hs : List H) (n : N) :
    nestedCommutator (hs.map SemidirectProduct.inr)
      (SemidirectProduct.inl n : N ⋊[φ] H) =
      SemidirectProduct.inl (iteratedDifference φ hs n) := by
  induction hs with
  | nil => rfl
  | cons h hs ih =>
    simp only [List.map_cons, nestedCommutator, List.foldr_cons] at ih ⊢
    rw [ih, semidirect_commutator]
    rfl

/-- An actual word for a product of arbitrary semidirect difference operators. -/
theorem iteratedDifference_rep {S : Set (N ⋊[φ] H)} {B : ℕ} (hs : List H) (n : N)
    (hn : WordRep S B (SemidirectProduct.inl n))
    (hh : ∀ h ∈ hs, WordRep S B (SemidirectProduct.inr h)) :
    WordRep S (3 * 2 ^ hs.length * B)
      (SemidirectProduct.inl (iteratedDifference φ hs n)) := by
  have h := nestedCommutator_rep_uniform (hs.map SemidirectProduct.inr) hn
    (by
      intro t ht
      obtain ⟨a, ha, rfl⟩ := List.mem_map.mp ht
      exact hh a ha)
  simpa only [List.length_map, nestedCommutator_inr_inl] using h

end Semidirect

section AdditiveDifference

variable {A : Type*} [AddCommGroup A] (α : AddAut A)

/-- The integral cyclic action generated by an additive automorphism. -/
def cyclicAction : Multiplicative ℤ →* MulAut (Multiplicative A) :=
  zpowersHom _ (AddEquiv.toMultiplicative α)

/-- The actual abelian-by-cyclic group associated to the specified automorphism. -/
abbrev CyclicSemidirect := Multiplicative A ⋊[cyclicAction α] Multiplicative ℤ

/-- Embed the normal additive group into the actual semidirect product. -/
def normalElement (v : A) : CyclicSemidirect α :=
  SemidirectProduct.inl (Multiplicative.ofAdd v)

/-- The stable letter in the actual cyclic factor. -/
def stableLetter : CyclicSemidirect α :=
  SemidirectProduct.inr (Multiplicative.ofAdd (1 : ℤ))

theorem normalElement_add (v w : A) :
    normalElement α (v + w) = normalElement α v * normalElement α w := by
  exact map_mul SemidirectProduct.inl _ _

theorem normalElement_zsmul (a : ℤ) (v : A) :
    normalElement α (a • v) = normalElement α v ^ a := by
  exact map_zpow SemidirectProduct.inl (Multiplicative.ofAdd v) a

/-- Difference of the `B`th action power and identity, as an additive homomorphism. -/
def powerDifference (B : ℕ) : AddMonoid.End A :=
  (AddEquiv.toMultiplicative.symm ((AddEquiv.toMultiplicative α) ^ B)).toAddMonoidHom -
    AddMonoidHom.id A

theorem cyclicAction_pow_one (B : ℕ) :
    cyclicAction α ((Multiplicative.ofAdd (1 : ℤ)) ^ B) =
      (AddEquiv.toMultiplicative α) ^ B := by
  rw [map_pow]
  congr 1

theorem stableLetter_pow_commutator (B : ℕ) (v : A) :
    stableLetter α ^ B * normalElement α v * (stableLetter α ^ B)⁻¹ *
      (normalElement α v)⁻¹ = normalElement α (powerDifference α B v) := by
  unfold stableLetter normalElement
  rw [← map_pow, semidirect_commutator]
  apply congrArg SemidirectProduct.inl
  unfold commutatorDifference
  rw [cyclicAction_pow_one]
  change (AddEquiv.toMultiplicative α ^ B) (Multiplicative.ofAdd v) *
      (Multiplicative.ofAdd v)⁻¹ =
    Multiplicative.ofAdd (((AddEquiv.toMultiplicative α ^ B)
      (Multiplicative.ofAdd v)).toAdd - v)
  simp [div_eq_mul_inv]

theorem stableLetter_commutator (v : A) :
    stableLetter α * normalElement α v * (stableLetter α)⁻¹ *
      (normalElement α v)⁻¹ = normalElement α (α v - v) := by
  have hd : powerDifference α 1 v = α v - v := by
    change ((AddEquiv.toMultiplicative α ^ 1) (Multiplicative.ofAdd v)).toAdd - v = _
    simp
  simpa only [pow_one, hd] using stableLetter_pow_commutator α 1 v

/-- Nested commutators with prescribed natural powers of the stable letter
implement exactly the corresponding additive difference operators. -/
theorem nested_power_difference (bs : List ℕ) (v : A) :
    nestedCommutator (bs.map (fun b => stableLetter α ^ b)) (normalElement α v) =
      normalElement α (bs.foldr (fun b w => powerDifference α b w) v) := by
  induction bs with
  | nil => rfl
  | cons b bs ih =>
    simp only [List.map_cons, nestedCommutator, List.foldr_cons] at ih ⊢
    rw [ih, stableLetter_pow_commutator]

/-- Actual digit words: a digit of size at most `B` and at most `d` commutators
with powers at most `B` give length at most `3·2^d·B`. -/
theorem digit_commutator_word {S : Set (CyclicSemidirect α)} {B : ℕ}
    (e : A) (he : normalElement α e ∈ S) (ht : stableLetter α ∈ S)
    (a : ℤ) (ha : a.natAbs ≤ B) (bs : List ℕ)
    (hb : ∀ b ∈ bs, b ≤ B) :
    WordRep S (3 * 2 ^ bs.length * B)
      (normalElement α (bs.foldr (fun b w => powerDifference α b w) (a • e))) := by
  have heword : WordRep S B (normalElement α (a • e)) := by
    rw [normalElement_zsmul]
    simpa using ((WordRep.generator he).zpow a).mono (by simpa using ha)
  have hword := nestedCommutator_rep_uniform
    (bs.map (fun b => stableLetter α ^ b)) heword (by
      intro t hmem
      obtain ⟨b, hbmem, rfl⟩ := List.mem_map.mp hmem
      simpa using ((WordRep.generator ht).pow b).mono (by simpa using hb b hbmem))
  simpa only [List.length_map, nested_power_difference] using hword

end AdditiveDifference

/-- Compression passes from a positive fixed power to the original element.
This is the division-with-remainder part of the rational-lattice reduction. -/
theorem compression_of_power {S : Set G} (g : G) (D C L j : ℕ)
    (hD : 1 ≤ D) (hg : WordRep S L g)
    (hcompressed : ∀ B : ℕ, 1 ≤ B → ∀ a : ℤ, a.natAbs ≤ B ^ j →
      WordRep S (C * B) ((g ^ D) ^ a)) :
    ∀ B : ℕ, 1 ≤ B → ∀ a : ℤ, a.natAbs ≤ B ^ j →
      WordRep S ((C + D * L) * B) (g ^ a) := by
  intro B hB a ha
  have hq : (a / (D : ℤ)).natAbs ≤ B ^ j :=
    (Int.natAbs_ediv_le_natAbs _ _).trans ha
  have hDn : (0 : ℤ) < D := by omega
  have hr0 := Int.emod_nonneg a (ne_of_gt hDn)
  have hrlt := Int.emod_lt_of_pos a hDn
  have hr : (a % (D : ℤ)).natAbs ≤ D := by
    have hcast : ((a % (D : ℤ)).natAbs : ℤ) ≤ D := by
      rw [Int.natAbs_of_nonneg hr0]
      omega
    exact_mod_cast hcast
  have hwords := (hcompressed B hB (a / D) hq).mul
    ((hg.zpow (a % D)).mono (Nat.mul_le_mul_right L hr))
  have heq : (g ^ D) ^ (a / (D : ℤ)) * g ^ (a % (D : ℤ)) = g ^ a := by
    rw [← zpow_natCast g D, ← zpow_mul, ← zpow_add]
    congr 1
    exact Int.mul_ediv_add_emod a D
  rw [heq] at hwords
  apply hwords.mono
  rw [Nat.add_mul]
  exact Nat.add_le_add_left (by simpa using Nat.mul_le_mul_left (D * L) hB) _

section PolynomialCoefficients

open Polynomial
open scoped BigOperators

/-- The nonconstant part of `(1+X)^B`, with nonnegative integral coefficients. -/
noncomputable def differencePolynomial (B : ℕ) : ℕ[X] := ((1 + X) ^ B).erase 0

theorem differencePolynomial_coeff (B i : ℕ) :
    (differencePolynomial B).coeff i = if i = 0 then 0 else B.choose i := by
  simp [differencePolynomial, Polynomial.coeff_erase, Polynomial.coeff_one_add_X_pow]

theorem differencePolynomial_coeff_le (B i : ℕ) :
    (differencePolynomial B).coeff i ≤ B ^ i := by
  rw [differencePolynomial_coeff]
  split_ifs
  · exact Nat.zero_le _
  · exact Nat.choose_le_pow B i

/-- Coefficient growth under multiplication, on the degrees that survive in a
Jordan block of size `ell`. -/
theorem truncated_coeff_mul_bound {ell B C D : ℕ} {p q : ℕ[X]}
    (hp : ∀ i < ell, p.coeff i ≤ C * B ^ i)
    (hq : ∀ i < ell, q.coeff i ≤ D * B ^ i)
    (i : ℕ) (hi : i < ell) :
    (p * q).coeff i ≤ (ell * C * D) * B ^ i := by
  rw [Polynomial.coeff_mul]
  calc
    ∑ a ∈ Finset.antidiagonal i, p.coeff a.1 * q.coeff a.2 ≤
        ∑ _a ∈ Finset.antidiagonal i, C * D * B ^ i := by
      apply Finset.sum_le_sum
      intro a ha
      have hab := Finset.mem_antidiagonal.mp ha
      calc
        p.coeff a.1 * q.coeff a.2 ≤ (C * B ^ a.1) * (D * B ^ a.2) :=
          Nat.mul_le_mul (hp _ (by omega)) (hq _ (by omega))
        _ = C * D * B ^ i := by rw [← hab, pow_add]; ring
    _ = (i + 1) * (C * D * B ^ i) := by simp
    _ ≤ ell * (C * D * B ^ i) := Nat.mul_le_mul_right _ (by omega)
    _ = (ell * C * D) * B ^ i := by ring

/-- Uniform polynomial coefficient estimate for every iterated large-step
difference operator, in every degree below the block size. -/
theorem differencePolynomial_pow_coeff_le (ell B u i : ℕ) (hi : i < ell) :
    ((differencePolynomial B) ^ u).coeff i ≤ ell ^ u * B ^ i := by
  induction u generalizing i with
  | zero =>
    by_cases h : i = 0
    · subst i; simp
    · simp [Polynomial.coeff_one, h]
  | succ u ih =>
    rw [pow_succ]
    have h := truncated_coeff_mul_bound (C := ell ^ u) (D := 1)
      (fun k hk => ih k hk)
      (fun k _ => by simpa using differencePolynomial_coeff_le B k) i hi
    simpa [pow_succ, Nat.mul_assoc, Nat.mul_comm, Nat.mul_left_comm] using h

/-- The lowest-degree monomial in the `u`th large-step difference is
`B^u X^u`; all lower coefficients vanish. -/
theorem differencePolynomial_pow_initial (B u : ℕ) :
    ((differencePolynomial B) ^ u).coeff u = B ^ u ∧
      ∀ i < u, ((differencePolynomial B) ^ u).coeff i = 0 := by
  have hd : (X : ℕ[X]) ∣ differencePolynomial B := by
    apply Polynomial.X_dvd_iff.mpr
    simp [differencePolynomial_coeff]
  have hdu : (X : ℕ[X]) ^ u ∣ differencePolynomial B ^ u := pow_dvd_pow_of_dvd hd u
  obtain ⟨q, hq⟩ := hd
  have hq0 : q.coeff 0 = B := by
    have h := congrArg (fun p : ℕ[X] => p.coeff 1) hq
    simpa [differencePolynomial_coeff] using h.symm
  constructor
  · rw [hq, mul_pow]
    have hc := Polynomial.coeff_X_pow_mul (q ^ u) u 0
    rw [zero_add] at hc
    rw [hc]
    change Polynomial.constantCoeff (q ^ u) = B ^ u
    rw [map_pow]
    exact congrArg (fun n : ℕ => n ^ u) hq0
  · intro i hi
    exact Polynomial.X_pow_dvd_iff.mp hdu i hi

/-- The polynomial represented by a digit commutator: `u` large-step
commutators, `v` unit-step commutators, and digit `a`. -/
noncomputable def digitPolynomial (B a u v : ℕ) : ℕ[X] :=
  C a * differencePolynomial B ^ u * X ^ v

theorem digitPolynomial_initial (B a u v : ℕ) :
    (digitPolynomial B a u v).coeff (u + v) = a * B ^ u ∧
      ∀ i < u + v, (digitPolynomial B a u v).coeff i = 0 := by
  have hd : (X : ℕ[X]) ∣ differencePolynomial B :=
    Polynomial.X_dvd_iff.mpr (by simp [differencePolynomial_coeff])
  have hdu := pow_dvd_pow_of_dvd hd u
  obtain ⟨q, hq⟩ := hdu
  constructor
  · rw [digitPolynomial, Polynomial.coeff_mul_X_pow, Polynomial.coeff_C_mul,
      (differencePolynomial_pow_initial B u).1]
  · intro i hi
    have heq : digitPolynomial B a u v = X ^ (u + v) * (C a * q) := by
      rw [digitPolynomial, hq, pow_add]
      ring
    rw [heq]
    exact Polynomial.X_pow_dvd_iff.mp (dvd_mul_right _ _) i hi

/-- Uniform bound for every error coordinate of an individual digit word.
Coordinate `i` here is zero based, hence its weight is `i+1`. -/
theorem digitPolynomial_coeff_le (ell B a u v i : ℕ)
    (hB : 1 ≤ B) (ha : a ≤ B) (hi : i < ell) :
    (digitPolynomial B a u v).coeff i ≤ ell ^ u * B ^ (i + 1) := by
  rw [digitPolynomial, Polynomial.coeff_mul_X_pow']
  split_ifs with hv
  · rw [Polynomial.coeff_C_mul]
    have hcoeff := differencePolynomial_pow_coeff_le ell B u (i - v) (by omega)
    calc
      a * (differencePolynomial B ^ u).coeff (i - v) ≤
          B * (ell ^ u * B ^ (i - v)) := Nat.mul_le_mul ha hcoeff
      _ = ell ^ u * B ^ (i - v + 1) := by rw [pow_succ]; ring
      _ ≤ ell ^ u * B ^ (i + 1) := by
        exact Nat.mul_le_mul_left _ (Nat.pow_le_pow_right hB (by omega))
  · exact Nat.zero_le _

theorem differencePolynomial_add_one (B : ℕ) :
    differencePolynomial B + 1 = (1 + X : ℕ[X]) ^ B := by
  have h := Polynomial.monomial_add_erase ((1 + X : ℕ[X]) ^ B) 0
  simpa [differencePolynomial, Polynomial.coeff_one_add_X_pow, add_comm] using h

/-- Evaluation into an arbitrary ring, including a noncommutative endomorphism
or matrix ring: natural coefficients commute with every element. -/
noncomputable def natPolynomialEval {R : Type*} [Semiring R] (N : R) : ℕ[X] →+* R :=
  Polynomial.eval₂RingHom' (Nat.castRingHom R) N (fun a => Nat.cast_commute a N)

@[simp] theorem natPolynomialEval_X {R : Type*} [Semiring R] (N : R) :
    natPolynomialEval N X = N := by
  simp [natPolynomialEval]

/-- The polynomial coefficient estimates apply to the actual difference
operator `(1+N)^B-1`, without assuming any distortion bound. -/
theorem natPolynomialEval_difference {R : Type*} [Ring R] (N : R) (B : ℕ) :
    natPolynomialEval N (differencePolynomial B) = (1 + N) ^ B - 1 := by
  apply eq_sub_iff_add_eq.mpr
  have h := congrArg (natPolynomialEval N) (differencePolynomial_add_one B)
  simpa only [map_add, map_one, map_pow, natPolynomialEval_X] using h

theorem natPolynomialEval_digit {R : Type*} [Ring R] (N : R) (B a u v : ℕ) :
    natPolynomialEval N (digitPolynomial B a u v) =
      (a : R) * ((1 + N) ^ B - 1) ^ u * N ^ v := by
  simp [digitPolynomial, map_mul, map_pow, natPolynomialEval_difference,
    natPolynomialEval_X]

end PolynomialCoefficients

section OperatorBridge

variable {A : Type*} [AddCommGroup A] (α : AddAut A)

def automorphismEnd : AddMonoid.End A := α.toAddMonoidHom

theorem automorphism_power_apply (B : ℕ) (v : A) :
    (AddEquiv.toMultiplicative α ^ B) (Multiplicative.ofAdd v) =
      Multiplicative.ofAdd (((automorphismEnd α) ^ B) v) := by
  induction B generalizing v with
  | zero => rfl
  | succ B ih =>
    rw [pow_succ, pow_succ, MulAut.mul_apply]
    exact ih (α v)

theorem powerDifference_eq (B : ℕ) :
    powerDifference α B = (automorphismEnd α) ^ B - 1 := by
  ext v
  change ((AddEquiv.toMultiplicative α ^ B) (Multiplicative.ofAdd v)).toAdd - v =
    ((automorphismEnd α) ^ B) v - v
  rw [automorphism_power_apply]
  rfl

/-- The abstract action difference is the evaluated binomial-difference
polynomial whenever the action is `I+N`. -/
theorem powerDifference_eq_evaluation (N : AddMonoid.End A)
    (hα : automorphismEnd α = 1 + N) (B : ℕ) :
    powerDifference α B = natPolynomialEval N (differencePolynomial B) := by
  rw [powerDifference_eq, hα, natPolynomialEval_difference]

theorem foldr_replicate_difference (B u : ℕ) (v : A) :
    (List.replicate u B).foldr (fun b w => powerDifference α b w) v =
      (powerDifference α B ^ u) v := by
  induction u with
  | zero => rfl
  | succ u ih =>
    simp only [List.replicate_succ, List.foldr_cons, ih, pow_succ']
    rfl

/-- The exact operator expression of a digit word, now connected to the actual
cyclic semidirect product and its generator words. -/
theorem digit_operator_word {S : Set (CyclicSemidirect α)}
    (N : AddMonoid.End A) (hα : automorphismEnd α = 1 + N)
    (e : A) (he : normalElement α e ∈ S) (ht : stableLetter α ∈ S)
    (B a u v : ℕ) (hB : 1 ≤ B) (ha : a ≤ B) :
    WordRep S (3 * 2 ^ (u + v) * B)
      (normalElement α ((natPolynomialEval N (digitPolynomial B a u v)) e)) := by
  have hw := digit_commutator_word α e he ht (a : ℤ) (by simpa using ha)
    (List.replicate u B ++ List.replicate v 1) (by
      intro b hb
      rcases List.mem_append.mp hb with hb | hb
      · exact (List.mem_replicate.mp hb).2 ▸ le_rfl
      · exact (List.mem_replicate.mp hb).2 ▸ hB)
  have h1 : powerDifference α 1 = N := by
    rw [powerDifference_eq, pow_one, hα]
    abel
  simp only [List.foldr_append, foldr_replicate_difference, List.length_append,
    List.length_replicate, h1] at hw
  rw [powerDifference_eq_evaluation α N hα] at hw
  rw [natPolynomialEval_digit]
  have heq : ((a : AddMonoid.End A) * ((1 + N) ^ B - 1) ^ u * N ^ v) e =
      ((natPolynomialEval N (differencePolynomial B)) ^ u) ((N ^ v) ((a : ℤ) • e)) := by
    rw [natPolynomialEval_difference]
    change a • (((1 + N) ^ B - 1) ^ u) ((N ^ v) e) =
      (((1 + N) ^ B - 1) ^ u) ((N ^ v) ((a : ℤ) • e))
    simp only [natCast_zsmul, map_nsmul]
  rw [heq]
  exact hw

end OperatorBridge

section NilpotentEvaluation

open scoped BigOperators

/-- In a nilpotent operator, evaluation is exactly the finite sum of the
coefficients below its nilpotence index. -/
theorem natPolynomialEval_truncated {R : Type*} [Ring R] (N : R) (ell : ℕ)
    (hN : N ^ ell = 0) (p : Polynomial ℕ) :
    natPolynomialEval N p = ∑ i ∈ Finset.range ell, (p.coeff i : R) * N ^ i := by
  classical
  change Polynomial.eval₂ (Nat.castRingHom R) N p = _
  rw [Polynomial.eval₂_eq_sum, Polynomial.sum_def]
  calc
    ∑ i ∈ p.support, (Nat.castRingHom R) (p.coeff i) * N ^ i =
        ∑ i ∈ p.support ∪ Finset.range ell, (p.coeff i : R) * N ^ i := by
      apply Finset.sum_subset Finset.subset_union_left
      intro i _ hi
      simp [Polynomial.notMem_support_iff.mp hi]
    _ = ∑ i ∈ Finset.range ell, (p.coeff i : R) * N ^ i := by
      symm
      apply Finset.sum_subset Finset.subset_union_right
      intro i _ hi
      have hpow : N ^ i = 0 := pow_eq_zero_of_le (by simpa using hi) hN
      simp [hpow]

/-- The coordinates appearing in a digit word are the polynomial coefficients
along the nilpotent chain `e,N(e),...,N^(ell-1)(e)`. -/
theorem natPolynomialEval_chain {A : Type*} [AddCommGroup A]
    (N : AddMonoid.End A) (ell : ℕ) (hN : N ^ ell = 0)
    (p : Polynomial ℕ) (e : A) :
    (natPolynomialEval N p) e =
      ∑ i ∈ Finset.range ell, p.coeff i • (N ^ i) e := by
  let ev : AddMonoid.End A →+ A :=
    { toFun := fun f => f e, map_zero' := rfl, map_add' := fun _ _ => rfl }
  have h := congrArg ev (natPolynomialEval_truncated N ell hN p)
  rw [map_sum] at h
  exact h

/-- Actual short words for the fully expanded digit-chain vectors. -/
theorem digit_chain_word {A : Type*} [AddCommGroup A] (α : AddAut A)
    {S : Set (CyclicSemidirect α)} (N : AddMonoid.End A)
    (hα : automorphismEnd α = 1 + N) (ell : ℕ) (hN : N ^ ell = 0)
    (e : A) (he : normalElement α e ∈ S) (ht : stableLetter α ∈ S)
    (B a u v : ℕ) (hB : 1 ≤ B) (ha : a ≤ B) :
    WordRep S (3 * 2 ^ (u + v) * B)
      (normalElement α (∑ i ∈ Finset.range ell,
        (digitPolynomial B a u v).coeff i • (N ^ i) e)) := by
  rw [← natPolynomialEval_chain N ell hN]
  exact digit_operator_word α N hα e he ht B a u v hB ha

end NilpotentEvaluation

section Assembly

open scoped BigOperators

/-- Base expansion with exactly `j` digits, including trailing zero digits. -/
theorem bounded_base_digits (B j a : ℕ) (hB : 1 < B) (ha : a < B ^ j) :
    ∃ digits : List ℕ, digits.length = j ∧ (∀ d ∈ digits, d < B) ∧
      a = (digits.mapIdx (fun i d => d * B ^ i)).sum := by
  refine ⟨Nat.digitsAppend B j a, Nat.length_digitsAppend hB j ha,
    fun d hd => Nat.lt_of_mem_digitsAppend hB j d hd, ?_⟩
  rw [← Nat.ofDigits_eq_sum_mapIdx, Nat.digitsAppend,
    Nat.ofDigits_append_replicate_zero, Nat.ofDigits_digits]

/-- Concatenating words for vectors in the normal abelian group adds their
word-length budgets and represents their actual sum. -/
theorem normalElement_sum_rep {A I : Type*} [AddCommGroup A]
    (α : AddAut A) {S : Set (CyclicSemidirect α)} (s : Finset I) (f : I → A)
    (L : ℕ) (hf : ∀ i ∈ s, WordRep S L (normalElement α (f i))) :
    WordRep S (s.card * L) (normalElement α (∑ i ∈ s, f i)) := by
  classical
  induction s using Finset.induction_on with
  | empty => simpa [normalElement] using WordRep.one S
  | @insert i s hi ih =>
    have hfi := hf i (by simp)
    have hrest := ih (fun k hk => hf k (by simp [hk]))
    rw [Finset.sum_insert hi, normalElement_add, Finset.card_insert_of_notMem hi]
    simpa [Nat.add_mul, Nat.add_comm] using hfi.mul hrest

/-- The polynomial obtained by concatenating all the base digits at weight `j`. -/
noncomputable def digitApproximationPolynomial (B j : ℕ) (digits : Fin j → ℕ) :
    Polynomial ℕ :=
  ∑ u : Fin j, digitPolynomial B (digits u) u.val (j - 1 - u.val)

theorem digitApproximationPolynomial_initial (B j : ℕ) (hj : 1 ≤ j)
    (digits : Fin j → ℕ) :
    (digitApproximationPolynomial B j digits).coeff (j - 1) =
      ∑ u : Fin j, digits u * B ^ u.val := by
  rw [digitApproximationPolynomial, Polynomial.finsetSum_coeff]
  apply Finset.sum_congr rfl
  intro u _
  have hu : u.val + (j - 1 - u.val) = j - 1 := by omega
  simpa only [hu] using (digitPolynomial_initial B (digits u) u.val
    (j - 1 - u.val)).1

/-- This is an actual word for the entire digit approximation, prior to
cancelling its higher coordinates. -/
theorem digit_approximation_word {A : Type*} [AddCommGroup A] (α : AddAut A)
    {S : Set (CyclicSemidirect α)} (N : AddMonoid.End A)
    (hα : automorphismEnd α = 1 + N) (e : A)
    (he : normalElement α e ∈ S) (ht : stableLetter α ∈ S)
    (B j : ℕ) (hB : 1 ≤ B) (hj : 1 ≤ j) (digits : Fin j → ℕ)
    (hd : ∀ u, digits u ≤ B) :
    WordRep S (j * (3 * 2 ^ (j - 1) * B))
      (normalElement α ((natPolynomialEval N
        (digitApproximationPolynomial B j digits)) e)) := by
  have hword := normalElement_sum_rep α Finset.univ
    (fun u : Fin j => (natPolynomialEval N
      (digitPolynomial B (digits u) u.val (j - 1 - u.val))) e)
    (3 * 2 ^ (j - 1) * B) (by
      intro u _
      have hu : u.val + (j - 1 - u.val) = j - 1 := by omega
      simpa only [hu] using
        digit_operator_word α N hα e he ht B (digits u) u.val
          (j - 1 - u.val) hB (hd u))
  have hsum : (natPolynomialEval N (digitApproximationPolynomial B j digits)) e =
      ∑ u : Fin j, (natPolynomialEval N
        (digitPolynomial B (digits u) u.val (j - 1 - u.val))) e := by
    let ev : AddMonoid.End A →+ A :=
      { toFun := fun f => f e, map_zero' := rfl, map_add' := fun _ _ => rfl }
    change ev (natPolynomialEval N (digitApproximationPolynomial B j digits)) = _
    rw [digitApproximationPolynomial, map_sum, map_sum]
    rfl
  rw [hsum]
  simpa only [Finset.card_univ, Fintype.card_fin] using hword

/-- Finite-indexed base digits, in the form used by the word assembly theorem. -/
theorem bounded_digits_function (B j a : ℕ) (hB : 1 < B) (ha : a < B ^ j) :
    ∃ digits : Fin j → ℕ, (∀ u, digits u < B) ∧
      a = ∑ u : Fin j, digits u * B ^ u.val := by
  induction j generalizing a with
  | zero =>
    have ha0 : a = 0 := by simpa using ha
    subst a
    exact ⟨Fin.elim0, fun u => Fin.elim0 u, by simp⟩
  | succ j ih =>
    have hq : a / B < B ^ j := by
      apply (Nat.div_lt_iff_lt_mul (by omega)).2
      simpa [pow_succ] using ha
    obtain ⟨digits, hd, hsum⟩ := ih (a / B) hq
    refine ⟨Fin.cons (a % B) digits, ?_, ?_⟩
    · intro u
      refine Fin.cases ?_ (fun u => ?_) u
      · exact Nat.mod_lt _ (by omega)
      · exact hd u
    · rw [Fin.sum_univ_succ]
      simp only [Fin.cons_zero, Fin.val_zero, pow_zero, mul_one, Fin.cons_succ,
        Fin.val_succ, pow_succ, ← mul_assoc, ← Finset.sum_mul, ← hsum]
      simpa [Nat.mul_comm] using (Nat.mod_add_div a B).symm

/-- All coordinates below the intended weight vanish in the assembled word. -/
theorem digitApproximationPolynomial_below (B j : ℕ) (hj : 1 ≤ j)
    (digits : Fin j → ℕ) (i : ℕ) (hi : i < j - 1) :
    (digitApproximationPolynomial B j digits).coeff i = 0 := by
  rw [digitApproximationPolynomial, Polynomial.finsetSum_coeff]
  apply Finset.sum_eq_zero
  intro u _
  exact (digitPolynomial_initial B (digits u) u.val (j - 1 - u.val)).2 i (by omega)

/-- Every higher coordinate of the assembled digit word has the required
weighted bound, with a constant depending only on the block size. -/
theorem digitApproximationPolynomial_coeff_le (ell B j : ℕ)
    (hB : 1 ≤ B) (_hj : 1 ≤ j) (hjell : j ≤ ell) (digits : Fin j → ℕ)
    (hd : ∀ u, digits u ≤ B) (i : ℕ) (hi : i < ell) :
    (digitApproximationPolynomial B j digits).coeff i ≤ ell ^ (ell + 1) * B ^ (i + 1) := by
  rw [digitApproximationPolynomial, Polynomial.finsetSum_coeff]
  calc
    ∑ u : Fin j, (digitPolynomial B (digits u) u.val (j - 1 - u.val)).coeff i ≤
        ∑ _u : Fin j, ell ^ ell * B ^ (i + 1) := by
      apply Finset.sum_le_sum
      intro u _
      apply (digitPolynomial_coeff_le ell B (digits u) u.val (j - 1 - u.val)
        i hB (hd u) hi).trans
      exact Nat.mul_le_mul_right _ (Nat.pow_le_pow_right (by omega) (by omega))
    _ = j * (ell ^ ell * B ^ (i + 1)) := by simp
    _ ≤ ell * (ell ^ ell * B ^ (i + 1)) := Nat.mul_le_mul_right _ hjell
    _ = ell ^ (ell + 1) * B ^ (i + 1) := by rw [pow_succ]; ring

/-- The constructive approximation step for every chain length and weight.
It produces the exact desired coefficient, zero lower coordinates, controlled
higher coordinates, and an actual word linear in the base `B`. -/
theorem chain_approximation {A : Type*} [AddCommGroup A] (α : AddAut A)
    {S : Set (CyclicSemidirect α)} (N : AddMonoid.End A)
    (hα : automorphismEnd α = 1 + N) (e : A)
    (he : normalElement α e ∈ S) (ht : stableLetter α ∈ S)
    (ell B j a : ℕ) (hB : 1 < B) (hj : 1 ≤ j) (hjell : j ≤ ell)
    (ha : a < B ^ j) :
    ∃ p : Polynomial ℕ,
      p.coeff (j - 1) = a ∧
      (∀ i < j - 1, p.coeff i = 0) ∧
      (∀ i < ell, p.coeff i ≤ ell ^ (ell + 1) * B ^ (i + 1)) ∧
      WordRep S (j * (3 * 2 ^ (j - 1) * B))
        (normalElement α ((natPolynomialEval N p) e)) := by
  obtain ⟨digits, hd, haeq⟩ := bounded_digits_function B j a hB ha
  refine ⟨digitApproximationPolynomial B j digits, ?_, ?_, ?_, ?_⟩
  · rw [digitApproximationPolynomial_initial B j hj, ← haeq]
  · exact digitApproximationPolynomial_below B j hj digits
  · exact digitApproximationPolynomial_coeff_le ell B j (by omega) hj hjell digits
      (fun u => (hd u).le)
  · exact digit_approximation_word α N hα e he ht B j (by omega) hj digits
      (fun u => (hd u).le)

/-- The top-weight case of chain compression has no error coordinates and is
fully obtained from the constructed words. This is the descending induction base. -/
theorem top_chain_compression {A : Type*} [AddCommGroup A] (α : AddAut A)
    {S : Set (CyclicSemidirect α)} (N : AddMonoid.End A)
    (hα : automorphismEnd α = 1 + N) (e : A)
    (he : normalElement α e ∈ S) (ht : stableLetter α ∈ S)
    (ell B a : ℕ) (hell : 1 ≤ ell) (hN : N ^ ell = 0)
    (hB : 1 < B) (ha : a < B ^ ell) :
    WordRep S (ell * (3 * 2 ^ (ell - 1) * B))
      (normalElement α (a • (N ^ (ell - 1)) e)) := by
  obtain ⟨p, hp, hlo, _, hw⟩ :=
    chain_approximation α N hα e he ht ell B ell a hB hell le_rfl ha
  rw [natPolynomialEval_chain N ell hN] at hw
  have hsum : (∑ i ∈ Finset.range ell, p.coeff i • (N ^ i) e) =
      a • (N ^ (ell - 1)) e := by
    rw [Finset.sum_eq_single (ell - 1)]
    · rw [hp]
    · intro i hi hne
      rw [hlo i (by have := Finset.mem_range.mp hi; omega), zero_nsmul]
    · intro hnot
      exact False.elim (hnot (Finset.mem_range.mpr (by omega)))
  rwa [hsum] at hw

end Assembly

end NilpotentConjugacy
